openapi: 3.0.3

info:
  title: Orders API
  description: API that allows you to manage orders for CoffeeMesh
  version: 1.0.0

paths:
  /orders/{order_id}/cancel:
    parameters:
      - in: path
        name: order_id
        required: true
        schema:
          type: string
          foramt: uuid
    post:
      summary: Cancel the order
      operationId: cancelOrder
      responses:
        '200':
          description: A JSON representation of canceled order
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetOrderSchema'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'

  /orders/{order_id}/pay:
    parameters:
      - in: path
        name: order_id
        required: true
        schema:
          type: string
          foramt: uuid
    post:
      summary: Update the status of order
      operationId: payOrder
      responses:
        '200':
          description: A JSON representation of the paid order 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetOrderSchema'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'

  /orders/{order_id}:
    parameters:
      - in: path
        name: order_id
        required: true
        schema:
          type: string
          foramt: uuid
    delete:
      summary: Deletes an existing order
      operationId: deleteOrder
      responses:
        '204':
          description: The resource was deleted successfully
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
    put:
      parameters:
        - in: path
          name: order_id
          required: true
          schema:
            type: string
            foramt: uuid
      summary: Update a order with id
      operationId: updateOrderById
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateOrderSchema"
      responses:
        '200':
          description: A JSON representation of the created order 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetOrderSchema'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'

    get:
      summary: Returns a order with id
      operationId: getOrderById
      responses:
        '200':
          description: A JSON object of order
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  oreders:
                    schema:  
                      $ref: '#/components/schemas/GetOrderSchema'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '404':
          $ref: '#/components/responses/NotFound'

  /orders:
    get:
      parameters:
      - name: cancelled
        in: query
        required: false
        schema:
          type: boolean
      - name: limit
        in: query
        required: false
        schema:
          type: integer
      summary: Returns a list of orders
      operationId: getOrders
      responses:
        '200':
          description: A JSON array of orders
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  orders:
                    type: array
                    items:
                      $ref: '#/components/schemas/GetOrdersSchema'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
          
    post:
      summary: Creates an order
      operationId: createOrder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateOrderSchema"
      responses:
        "201":
          description: A JSON representation of the created order 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetOrderSchema'
        "422":
          $ref: '#/components/responses/UnprocessableEntity'

components:
  responses:
    UnprocessableEntity:
      description: The payload contains invalid values.
      content:
        application/json:
          schema: 
            'ref': '#/components/schemas/Error'

    NotFound:
      description: The specified resource was not found.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  securitySchemes:
    openId:
      type: openIdConnect
      openIdConnectUrl: https://coffeemesh-dev.eu.auth0.com/.well-known/openid-configuration
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://coffeemesh-dev.eu.auth0.com/oauth/token
          scopes: {}
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Error:
      type: object
      properties:
        detail:
          oneOf:
            - type: string
            - type: array
      required:
        - detail

    OrderItemSchema:
      additionalProperties: false
      type: object
      required:
        - product
        - size
      properties:
        product:
          type: string
        size:
          type: string
          enum:
            - small
            - medium
            - big
          quantity:
            type: integer
            format: int64
            default: 1
            minimum: 1
            maximum: 100000
          
    GetOrderSchema:
      additionalProperties: false
      type: object
      required:
        - id
        - created
        - status
        - order
      properties:
        id:
          type: string
          format: uuid
        created:
          type: string
          format: date-time
        status:
          type: string
          enum:
            - created
            - paid
            - progress
            - cancelled
            - dispatched
            - delivered
        order:
          schema:
            $ref: "#/components/schemas/OrderItemSchema"
    
    GetOrdersSchema:
      additionalProperties: false
      type: object
      orders:
          type: array
          items:
            $ref: "#/components/schemas/OrderItemSchema"

    CreateOrderSchema:
      additionalProperties: false
      type: object
      required:
        - order
      properties:
        order:
          schema: 
            $ref: "#/components/schemas/OrderItemSchema"